export const SEARCH_REQUEST="SEARCH_REQUEST";
export const SEARCH_SUCCESS="SEARCH_SUCCESS";
export const SEARCH_FAILURE="SEARCH_FAILURE";

export const RECIPE_REQUEST="RECIPE_REQUEST";
export const RECIPE_SUCCESS="RECIPE_SUCCESS";
export const RECIPE_FAILURE="RECIPE_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";